"""Initial Migration

Revision ID: 521985cc5ad1
Revises: 
Create Date: 2024-07-02 14:44:17.054894

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '521985cc5ad1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_password', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('date_added', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('date_added')
        batch_op.drop_column('user_password')

    # ### end Alembic commands ###
